apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:C6M63H6ZmeBQHn84T5oxXHNZb3JFLoIO4tbLgB2P+7C1hIbuWms/xg==,iv:0s9xjqxLj3Lz13GR6NBNe4naSCWzOawHmXvUptzrb0M=,tag:n4Jt114EXTGurFE1WOBqkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eq7aeal9sq4v2kj8kr2wp25ayffzhuq35l5plpl27620lemek4dqqqtnty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRVdiN0llRmN6dHhsQVdD
            VHZ6ai8zY0c1YUxweThLUGpFS0xSSVkxT1hzCjFoU0M5dVlNSlJXSEg1YURNSk1K
            TkM4bWR6NzhFM3pRTWVSYlBUVjFOdTQKLS0tIFROTGYwcFA0OHlTZzFNaWtycFZY
            aGM0cXhGRUh1dHJWeGcrRHh3MHZoUU0KMKJbxFr/MVU9n7M+XH+t0VkK8jNYaORI
            fstSvI0GIQz0SMncNhqPO+fGq+YEFB5Wj8fkue6ZeXh1FuCZ3V3f2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T06:19:25Z"
    mac: ENC[AES256_GCM,data:RAvMoOobk0rIKWepFTDgJ83V6wB+MqYH5Y+0aVZL6691ZJp49DjvhxFRUo1MmpFYot9ujznRAEXsEzimYDKAsMdp8ReHt2uul44+xZBAYwKj1BLKpHjE6AQHOMgAl/uvUy9EOI6YI4+UYURlsNZUMsAB6EL1FxbBNqK/PQTXd7o=,iv:vF5HuYNH1khyGfCv7Qg6yDb9l7YfCcnaCOuhuII+18E=,tag:wkLNLK6iL/vuwEiYDFqGHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
