apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:HxaYFebs4RquJaxVZwv7cA7wxQ/VncWkbp39f7HBz6lPGhjTm6/feQ==,iv:p5aFb8HvKJ0mL4KUMOicvcz0m4SNhxPHF0SBXfLzLPY=,tag:oqa+2QBCGnW9+uClByH43A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eq7aeal9sq4v2kj8kr2wp25ayffzhuq35l5plpl27620lemek4dqqqtnty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c3AwUytReTlUOEVacVFa
            S1loT2ZtTjB2cHlaM2JQblRrbmNKeXM2aDBZCmRvTkZtRVdhSXI0dnRhaktCZ094
            WTRFQThnR1cxYzNjT28wRGJzU3hDSVUKLS0tIExwTUY0Um5PcDlpcFpYWGJNVHBC
            RjFmY3BKcTFUOUoxbVhqQ2tkdzhpQWMKEvvEpVYESbKFcYqHDc72oiDWdqOaZWye
            BuekG9QozqEajuzceiZmo2yHfRVAlxPmpRzc4UK36E/+zAO9+SwDqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-23T07:06:09Z"
    mac: ENC[AES256_GCM,data:/cqK58er3nOe5G2c4QnL5qC2jQM4F62iX1QejzYQ04en9E7ZeuBiRyNtSFtAuB7LGHQHRNsrA4rjRSPkx1wwyn3AgcSzG+rlCNYadgDWcV2FhJufN+Bi+Llsmku9DNtX/CIMRHSCSCMKtx6jBVaFbRknXhmpdEa53NLZDcxGOrM=,iv:MwkGuzzm9KVf8aL7cyDY2rEIQ/b0HqEsOw9FjcaDw1E=,tag:sEaGuqscSspYgnEFfgSmaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
