apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:guXGAmDP0BKnQgg2tYwTYA==,iv:48kZ1VR1+E3e5M1V2GYjL++VmK86rmt42hwm3X++g5o=,tag:7RbFl17NlbKmRn5GRWiz3g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:DKiqgRdKeH2VSp3oy2UgliconaPSTSTL,iv:2J+v0MqATR3eKTitvLlZTZtmjE0fbdKflr/gy0V3xkY=,tag:uR0T2kYuW1QjR4MeKtyvVA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:R8UWEKlJrn1RsbXKmdNlrEsFRyns7d1edJd05Zp0c1zUxQPn,iv:x7xN93n6OgiWCzOioCk0T1rsIYHhxbNCO95RcNZ1/js=,tag:SnFBrGP9OIL6vJKdrh/Ckw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eq7aeal9sq4v2kj8kr2wp25ayffzhuq35l5plpl27620lemek4dqqqtnty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZTRDQmNZZTI0QWxDOS9x
            ek5TdmEyeGVubUlUMTVSaXBySVhqWTNBV3dZCk11eEkwNmx1UkZwbVl1NFkrRzhx
            dENQaGxQR2x0dW5WblROVGRxUFZleHcKLS0tIFRKYjIyQUJ6K2hsRjJXUWRHNGJy
            Uk8yWlA5UEpHbDNGWUh2NkxMdWhTM1UK9bTOi5dOn8BgNYsgq+z7hCpVwU2fZc64
            pyw5WGOpb/GLmIiNugyim+AmWsF0rd3sC4VBy/tfK3XdxWEiCYntPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T05:55:53Z"
    mac: ENC[AES256_GCM,data:XJSofGU25/U0NdczyQX1ScV27ndySBCqYnGi6Hvvcm4cbzydQOMkMqU2ouGBTx+pJy1ypQQMf1fbQn1mzllwG8R7P5Rfp8voir/JH6Wf1uPcWH8FIyVBXIGJ/WN+oocfuCTpfqtzV2x2pteR8qGyjLddKD7DtbvhQV+ck8y4LbE=,iv:e4Ocdv8O25RFBfJNiP6+Yno0Hp958xicU4wVbsNWdls=,tag:mJdIjTh8szcM7eWRteJkig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
