apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:rZV5IzYp9kMCeW5TgpwL8BNcQfYK1NsiNyC+rdFJq/4=,iv:WLwHMBpUUCRlosLZHrhvHi+K8Znv7E2WhCWzWJU2kYI=,tag:LiASHOwqXu8tsHPj76tnbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eq7aeal9sq4v2kj8kr2wp25ayffzhuq35l5plpl27620lemek4dqqqtnty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlemJSWXV3MHdhbHpwQWI4
            U1pkeGI0a0lYQjVuVmZPTEM0OTM2a0czdGhnCnVPSlEyNnRrTmtKS0szUHRieTJ6
            NHIxMkZaVFlFUENmc1Z3TC82Rk1XVncKLS0tIHhId2JDSElSbUkzRWtGZmU3am15
            Z3hiVERWcEtvNUhlYjFaa2ExaWgxMzgKLIDk8RJILE96U6QllIKy3+j2rUN4AqS6
            mqvzwJ5Ebe0ObWcukJLsMcByYHzl/NltoqFbrwQ4BQNoC1RjrzBrxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T05:55:53Z"
    mac: ENC[AES256_GCM,data:KblCu7njU9Yunt9/8R6SqeHzfHutwg939n3ET9oIh8znLtIGuVNiq03hPffwY/D7kXKVMzoQn5BGWsBsT5tPBnSe2cVqduTPbL+MonMpScWyUnitmq+Ui3yMlRME5eOGQ/a5bjVV072ZRChSthXuHb7og0jJ4667L3QmXzglzVU=,iv:+Ck8yn9BYNfkAbwgEo2kUdPFDSQF5aikFPj1VUeBH38=,tag:azrhxyHyws9z/86SoOUODg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
